#ifndef DTT_CONFIG_H
#define DTT_CONFIG_H
#define DTT_REFLECT_AFTER_HITS 2
#define DTT_THREAD_TRACK_CAPACITY  128
#define DTT_THREAD_CLASS_OFFENSES  8
#define DTT_THREAD_NAME_MAX        64
#define DTT_CACHE_CAPACITY 512
#define DTT_CACHE_NAME_MAX 512
#define DTT_CACHE_MAX_CLASS_BYTES (8 * 1024 * 1024)
#define DTT_WATCHDOG_DEFAULT_INTERVAL_MS 4000
#define DTT_WATCHDOG_MIN_INTERVAL_MS      500
#define DTT_METHOD_TRACK_CAPACITY        2048

#endif /* DTT_CONFIG_H */